name: Daily MTA-STS Scraper

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Fetch MTA-STS Policy
      run: |
        curl -s https://mta-sts.protonmail.com/.well-known/mta-sts.txt > .well-known/mta-sts.txt

    - name: Commit and push updated file
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "36704600+noconnor29@users.noreply.github.com."
        git add .well-known/mta-sts.txt
        git commit -m "Update MTA-STS policy on $(date +'%Y-%m-%d')"
        git push
