name: Update DNS Record

on:
  push:
    paths:
      - ".well-known/mta-sts.txt" # Trigger only when the policy file changes
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-dns:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Fetch current DNS record
      id: fetch_dns
      run: |
        curl -s -X GET \
          -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          "https://api.cloudflare.com/client/v4/zones/${{ secrets.ZONE_ID }}/dns_records?type=TXT&name=_mta-sts.${{ secrets.DOMAIN }}" \          > dns_record.json
        cat dns_record.json

    - name: Update DNS record with new id
      run: |
        NEW_ID=$(date +'%Y%m%d%H%M%S') # Generate a unique ID
        RECORD_ID=$(jq -r '.result[0].id' dns_record.json) # Extract the record ID
        curl -s -X PUT \
          -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          "https://api.cloudflare.com/client/v4/zones/${{ vars.ZONE_ID }}/dns_records?type=TXT&name=_mta-sts.${{ vars.DOMAIN }}" \          --data '{
            "type": "TXT",
            "name": "_mta-sts.${{ vars.DOMAIN }}",
            "content": "v=STSv1; id='"$NEW_ID"'"
          }'
        echo "Updated _mta-sts record with id: $NEW_ID"
